#!/usr/bin/env Rscript

sys = modules::import('klmr/sys')
modules::import('klmr/functional/lambda')

clamp = function (x, min, max)
    pmin(pmax(x, min), max)

capitalize = function (str)
    paste0(toupper(substr(str, 1, 1)), substr(str, 2, nchar(str)))

sys$run({
    args = sys$cmd$parse(arg('tailinfo', 'tailinfo input file'),
                         opt('t', 'treatment', 'which treatment (infected, uninfected)',
                             validate = x -> x %in% c('infected', 'uninfected')),
                         opt('g', 'germline', 'the germline enriched gene list'),
                         opt('i', 'infection-response', 'the infection response gene list'),
                         opt('o', 'plot', 'plot output filename'))

    io = modules::import('ebi-predocs/ebits/io')
    modules::import_package('dplyr', attach = TRUE)
    modules::import_package('ggplot2', attach = TRUE)
    tidyr = modules::import_package('tidyr')
    modules::import('./theme', attach = TRUE)

    germline_genes = io$read_table(args$germline, header = TRUE)[[1]]
    infection_response_genes = io$read_table(args$infection_response, header = TRUE)[[1]]

    tailinfo = io$read_table(args$tailinfo, header = TRUE, na.strings = NA) %>%
        filter(Source == 'host') %>%
        mutate(palen = clamp(`pA length`, 0, 80))

    tail_fc = tailinfo %>%
        group_by(Type, Treatment, Gene, Sample) %>%
        summarize(palen = weighted.mean(palen, Support)) %>%
        summarize(palen = mean(palen)) %>%
        mutate(Germline = Gene %in% germline_genes,
               InfectionResponse = Gene %in% infection_response_genes) %>%
        ungroup() %>%
        tidyr$spread(Type, palen) %>%
        mutate(log2FC = log2(KO) - log2(WT))

    extended_tail_fc = bind_rows(mutate(tail_fc, Geneset = 'All'),
                                  filter(tail_fc, Germline) %>% mutate(Geneset = 'Germline'),
                                  filter(tail_fc, InfectionResponse) %>% mutate(Geneset = 'Infection response'))

    unicode_minus = if (tools::file_ext(args$plot) != 'pdf')
        function (x) sub('^-', '\U2212', format(x))
    else
        waiver()

    p = ggplot(extended_tail_fc) +
        aes(Geneset, log2FC, color = Geneset) +
        geom_jitter(width = 0.25, size = 0.5, alpha = 0.25) +
        geom_boxplot(outlier.color = NA, width = 0.5, color = 'gray20') +
        guides(color = FALSE) +
        labs(x = 'Gene set', y = expression(log[2]('fold change'))) +
        scale_x_discrete(labels = c('All', 'Germline', 'Infection\nresponse'),
                         limits = c('All', 'Germline', 'Infection response')) +
        scale_y_continuous(labels = unicode_minus)

    ggsave(args$plot, p, width = 3, height = 3, dpi = 1200)
})

# vim: ft=r
