#!/usr/bin/env Rscript

sys = modules::import('klmr/sys')

sys$run({
    args = sys$cmd$parse(arg('summary', 'tail summary file'),
                         opt('o', 'plot', 'plot output filename'))

    io = modules::import('ebi-predocs/ebits/io')
    modules::import_package('dplyr', attach = TRUE)
    modules::import_package('ggplot2', attach = TRUE)
    modules::import('./theme')

    viral_mod = io$read_table(args$summary, header = TRUE, na.strings = NA) %>%
        filter(Source != 'host', Mod == '' | Mod == 'T', Treatment == 'Infected') %>%
        select(-Mod, -Treatment) %>%
        mutate(Source = sub('-', '­', Source)) %>%
        group_by(Type, Source, ModLength) %>%
        mutate(min = min(Frequency), max = max(Frequency),
               Frequency = mean(Frequency)) %>%
        ungroup()

    dodge = position_dodge(width = 0.9)
    p = ggplot(viral_mod) +
        aes(x = ModLength, y = Frequency, fill = Type) +
        geom_bar(stat = 'identity', position = dodge) +
        geom_linerange(aes(ymin = min, ymax = max), position = dodge,
                       color = '#606060') +
        facet_wrap(~ Source, nrow = 2) +
        labs(x = 'Uridylation length', y = 'Fraction of reads')

    ggsave(args$plot, p, width = 4, height = 3)
})

# vim: ft=r
