#!/usr/bin/env Rscript

sys = modules::import('klmr/sys')

sys$run({
    args = sys$cmd$parse(arg('taginfo', 'input taginfo file'))

    io = modules::import('ebi-predocs/ebits/io')
    modules::import_package('dplyr', attach = TRUE)
    tidyr = modules::import_package('tidyr')

    taginfo = io$read_table(args$taginfo, header = TRUE)

    modules::import_package('ggplot2', attach = TRUE)

    pa_density_plot = ggplot() +
        aes(x = palen, y = ..density..) +
        geom_freqpoly(binwidth = 6) +
        scale_x_continuous(limits = c(0, 85), expand = c(0, 0)) +
        labs(x = 'poly-A length', y = 'Density of reads')

    #+ pA-density
    pa_density_plot %+%
        taginfo +
        aes(color = paste(type, treatment)) +
        labs(color = 'Condition')

    #+ viral-pa-density
    viral_taginfo = taginfo %>%
        filter(treatment == 'Uninfected') %>%
        mutate(`RNA source` = ifelse(grepl('ORV', gene, fixed = TRUE), gene, 'host'))

    darken = function (cols, factor = 2)
        rgb(t(col2rgb(cols) / factor), maxColorValue = 255)

    viral_colors = data_frame(`RNA source` = relevel(factor(unique(viral_taginfo$`RNA source`)), 'host'),
                              Color1 = c('gray', 'chocolate3', 'cadetblue3')) %>%
        mutate(Color2 = darken(Color1, 1.5)) %>%
        tidyr$gather(sample, Color, -`RNA source`) %>%
        mutate(sample = as.integer(gsub('Color', '', sample))) %>%
        {setNames(.$Color, paste(.$`RNA source`, .$sample))}

    pa_density_plot %+%
        viral_taginfo +
        aes(color = paste(`RNA source`, sample)) +
        scale_color_manual(values = viral_colors) +
        labs(color = 'RNA source')
})

# vim: ft=r
