#!/usr/bin/env Rscript

sys = modules::import('klmr/sys')

sys$run({
    args = sys$cmd$parse(arg('taginfo', 'input taginfo file'))

    io = modules::import('ebi-predocs/ebits/io')
    modules::import_package('dplyr', attach = TRUE)

    taginfo = io$read_table(args$taginfo, header = TRUE)

    # pA cumulative density

    modules::import_package('ggplot2', attach = TRUE)

    ggplot(taginfo) +
        aes(x = palen, y = ..density..) +
        geom_freqpoly(aes(color = treatment, linetype = type), binwidth = 6) +
        scale_x_continuous(limits = c(0, 100), expand = c(0, 0)) +
        coord_cartesian(xlim = c(0,80))
})

# vim: ft=r
